/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_aachen_comsys_audiosync_AudioCore */

#ifndef _Included_de_rwth_aachen_comsys_audiosync_AudioCore
#define _Included_de_rwth_aachen_comsys_audiosync_AudioCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_rwth_aachen_comsys_audiosync_AudioCore
 * Method:    initAudio
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_comsys_audiosync_AudioCore_initAudio
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_rwth_aachen_comsys_audiosync_AudioCore
 * Method:    startPlayback
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_comsys_audiosync_AudioCore_startPlayback
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     de_rwth_aachen_comsys_audiosync_AudioCore
 * Method:    startListening
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_comsys_audiosync_AudioCore_startListening
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_rwth_aachen_comsys_audiosync_AudioCore
 * Method:    stopPlayback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_comsys_audiosync_AudioCore_stopPlayback
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
